// ============================================================================
// Seed slate — the acquired firms in the roll-up.
// Each is a compact FirmSeed; buildFirm() runs it through the ingestion
// pipeline into a fully-normalized Firm.
// ============================================================================

import { buildFirm, FirmSeed } from './ingest';
import { Firm } from './types';

const SEEDS: FirmSeed[] = [
  {
    slug: 'meridian-tax-advisory',
    name: 'Meridian Tax & Advisory',
    hq: 'Denver, CO',
    founded: 1998,
    focus: 'Tax & advisory platform anchor',
    system: 'karbon',
    acquisitionDate: '2023-06-15',
    entryMultiple: 6.5,
    ownershipPct: 100,
    status: 'platform',
    integrationStage: 'integrated',
    accentColor: '#22c55e',
    revenueLTM: 14.2,
    ebitdaMarginPct: 31,
    mix: { tax: 0.35, audit: 0.05, cas: 0.25, advisory: 0.35 },
    recurring: { tax: 40, audit: 60, cas: 92, advisory: 70 },
    partners: 9,
    fte: 78,
    offshoreFte: 22,
    realizationPct: 90,
    utilizationPct: 76,
    wip: 1.1,
    ar: 1.6,
    arOver90: 0.3,
    clientCount: 620,
    top10ClientPct: 20,
    churnedLTM: 18,
    addedLTM: 40,
    netRetentionPct: 104,
    partnerComp: 520000,
    onshoreComp: 95000,
    offshoreComp: 28000,
    leadership: [
      { role: 'Managing Partner', name: 'Dana Whitfield', retentionRisk: 'low' },
      { role: 'Head of Advisory', name: 'Marcus Lin', retentionRisk: 'low' },
      { role: 'Tax Practice Lead', name: 'Priya Raman', retentionRisk: 'medium' },
    ],
  },
  {
    slug: 'caldwell-cpas',
    name: 'Caldwell & Co. CPAs',
    hq: 'Columbus, OH',
    founded: 1986,
    focus: 'Compliance-heavy tax, pricing upside',
    system: 'cch-axcess',
    acquisitionDate: '2024-02-01',
    entryMultiple: 5.2,
    ownershipPct: 100,
    status: 'performing',
    integrationStage: 'first-100',
    accentColor: '#3b82f6',
    revenueLTM: 8.6,
    ebitdaMarginPct: 22,
    mix: { tax: 0.62, audit: 0.1, cas: 0.2, advisory: 0.08 },
    recurring: { tax: 35, audit: 55, cas: 88, advisory: 60 },
    partners: 7,
    fte: 52,
    offshoreFte: 4,
    realizationPct: 74,
    utilizationPct: 64,
    wip: 1.0,
    ar: 1.5,
    arOver90: 0.5,
    clientCount: 940,
    top10ClientPct: 24,
    churnedLTM: 30,
    addedLTM: 22,
    netRetentionPct: 92,
    partnerComp: 410000,
    onshoreComp: 82000,
    offshoreComp: 26000,
    leadership: [
      { role: 'Managing Partner', name: 'Robert Caldwell', retentionRisk: 'medium' },
      { role: 'Tax Director', name: 'Susan Metz', retentionRisk: 'low' },
      { role: 'Ops Manager', name: 'Vacant', retentionRisk: 'high' },
    ],
  },
  {
    slug: 'summit-ledger',
    name: 'Summit Ledger',
    hq: 'Austin, TX',
    founded: 2011,
    focus: 'Client accounting services specialist',
    system: 'quickbooks',
    acquisitionDate: '2024-05-20',
    entryMultiple: 5.8,
    ownershipPct: 100,
    status: 'watch',
    integrationStage: 'first-100',
    accentColor: '#f59e0b',
    revenueLTM: 5.4,
    ebitdaMarginPct: 18,
    mix: { tax: 0.18, audit: 0.0, cas: 0.68, advisory: 0.14 },
    recurring: { tax: 30, audit: 0, cas: 95, advisory: 62 },
    partners: 4,
    fte: 46,
    offshoreFte: 12,
    realizationPct: 82,
    utilizationPct: 70,
    wip: 0.4,
    ar: 0.7,
    arOver90: 0.15,
    clientCount: 380,
    top10ClientPct: 30,
    churnedLTM: 20,
    addedLTM: 35,
    netRetentionPct: 96,
    partnerComp: 360000,
    onshoreComp: 72000,
    offshoreComp: 24000,
    leadership: [
      { role: 'Managing Partner', name: 'Elena Ruiz', retentionRisk: 'low' },
      { role: 'CAS Lead', name: 'Tom Becker', retentionRisk: 'medium' },
    ],
  },
  {
    slug: 'coastal-assurance',
    name: 'Coastal Assurance Partners',
    hq: 'Charleston, SC',
    founded: 1994,
    focus: 'Audit & assurance, concentration risk',
    system: 'cch-axcess',
    acquisitionDate: '2024-03-10',
    entryMultiple: 5.5,
    ownershipPct: 100,
    status: 'watch',
    integrationStage: 'first-100',
    accentColor: '#f97316',
    revenueLTM: 9.1,
    ebitdaMarginPct: 19,
    mix: { tax: 0.15, audit: 0.6, cas: 0.1, advisory: 0.15 },
    recurring: { tax: 35, audit: 65, cas: 90, advisory: 58 },
    partners: 8,
    fte: 61,
    offshoreFte: 6,
    realizationPct: 76,
    utilizationPct: 66,
    wip: 1.3,
    ar: 1.9,
    arOver90: 0.6,
    clientCount: 210,
    top10ClientPct: 42,
    churnedLTM: 12,
    addedLTM: 10,
    netRetentionPct: 90,
    partnerComp: 430000,
    onshoreComp: 88000,
    offshoreComp: 27000,
    leadership: [
      { role: 'Managing Partner', name: 'Grace Okoro', retentionRisk: 'low' },
      { role: 'Assurance Lead', name: 'Daniel Pope', retentionRisk: 'medium' },
      { role: 'Advisory Lead', name: 'Vacant', retentionRisk: 'high' },
    ],
  },
  {
    slug: 'hollis-cpa-group',
    name: 'Hollis CPA Group',
    hq: 'Wichita, KS',
    founded: 1979,
    focus: 'Legacy tax firm, succession turnaround',
    system: 'ultratax',
    acquisitionDate: '2024-07-01',
    entryMultiple: 4.6,
    ownershipPct: 100,
    status: 'turnaround',
    integrationStage: 'day-1',
    accentColor: '#ef4444',
    revenueLTM: 6.2,
    ebitdaMarginPct: 16,
    mix: { tax: 0.7, audit: 0.08, cas: 0.12, advisory: 0.1 },
    recurring: { tax: 32, audit: 50, cas: 85, advisory: 55 },
    partners: 6,
    fte: 38,
    offshoreFte: 0,
    realizationPct: 71,
    utilizationPct: 61,
    wip: 1.1,
    ar: 1.7,
    arOver90: 0.8,
    clientCount: 1100,
    top10ClientPct: 28,
    churnedLTM: 55,
    addedLTM: 18,
    netRetentionPct: 84,
    partnerComp: 350000,
    onshoreComp: 78000,
    offshoreComp: 0,
    leadership: [
      { role: 'Managing Partner', name: 'Bill Hollis', retentionRisk: 'high' },
      { role: 'Senior Partner', name: 'Frank Storey', retentionRisk: 'high' },
      { role: 'Tax Manager', name: 'Amy Nguyen', retentionRisk: 'medium' },
    ],
  },
];

export const firms: Firm[] = SEEDS.map(buildFirm);

export const firmsMap: Record<string, Firm> = Object.fromEntries(
  firms.map((f) => [f.slug, f])
);

export function getFirmBySlug(slug: string): Firm | undefined {
  return firmsMap[slug];
}

export const firmSeeds = SEEDS;
